stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

before_script:
  - apt-get update -qy
  - apt-get install -y maven

test:
  stage: test
  script:
    - mvn test
