image: maven:3.9.9-eclipse-temurin-23

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  script:
    - mvn test -Dtest=!TestPlayerController

