image: maven:3.9.9-eclipse-temurin-23

stages:
  - test
  - build
  - release

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  script:
    - mvn test -Dtest=!TestPlayerController

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mvn package -DskipTests
    - mkdir -p artifacts
    - cp target/musicApp-*.jar artifacts/
    - mv artifacts/*.jar artifacts/musicapp-${CI_COMMIT_TAG}.jar
  artifacts:
    paths:
      - artifacts/

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for version $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created from tag $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'MusicApp JAR'
          url: '${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/jobs/artifacts/${CI_COMMIT_TAG}/raw/artifacts/musicapp-${CI_COMMIT_TAG}.jar?job=build'
