image: maven:3.9.9-eclipse-temurin-23

stages:
  - test
  - build
  - release

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

test:
  stage: test
  script:
    - mvn test -Dtest=!TestPlayerController

build:
  stage: build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - mvn package -DskipTests
    - mkdir -p artifacts
    - cp target/*.jar artifacts/
  artifacts:
    paths:
      - artifacts/
    expire_in: 1 week

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - build
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Creating release for version $CI_COMMIT_TAG"
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release created from tag $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'JAR File'
          url: '${CI_PROJECT_URL}/-/jobs/${CI_JOB_ID}/artifacts/file/artifacts/${CI_PROJECT_NAME}*.jar'