name: CI/CD

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Run tests (excluding TestPlayerController)
        run: mvn test -Dtest=!TestPlayerController

  build:
    runs-on: ubuntu-latest
    name: Build JAR
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
      - name: Build project
        run: |
          mvn package -DskipTests
          mkdir -p artifacts
          cp target/musicApp-*.jar artifacts/
          TAG_NAME=${GITHUB_REF##*/}
          mv artifacts/*.jar artifacts/musicapp-${TAG_NAME}.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: musicapp-jar
          path: artifacts/musicapp-*.jar

  release:
    runs-on: ubuntu-latest
    name: Create GitHub Release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: musicapp-jar
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body: Release created from tag ${{ github.ref_name }}
          files: artifacts/musicapp-${{ github.ref_name }}.jar
